### PR TITLE
Add the packaging metadata to build the quassel-webserver snap

### PR DESCRIPTION
**Pull request by elopio**
This is a package for the secure installation of apps that works in most Linux distributions.
Landing it upstream will enable builds for adventurous users.

### CODE REVIEW

**Comment by elopio** [comment]
I've been trying to make a snap for quassel-webserver. You can find more information about snaps and snapcraft here: http://snapcraft.io/

Now I'm able to launch the application, but I'm getting a few errors: https://gist.github.com/elopio/e8a5214aa89a320ebd505b5dc184e2df

Would you be interested in providing a snap for your users? I've recently found out that quassel-client doesn't work on yakkety, so I'm looking for an alternative. This one looks pretty nice. Snaps have a few nice features, like transactional and automatic updates, complete isolation from other snaps, you can release on your own schedule independent of the distros release dates, and you have full control over your dependencies. 

If you have any doubts or comments, please let me know :)

**Comment by magne4000** [comment]
Did you made some progress on this ?

**Comment by elopio** [comment]
Oh hi @magne4000! I thought you were not interested. Now I see that the comments in gists don't trigger notifications, so I missed yours.
I've been trying to dig into this, but I don't know enough javascript. 

The only error in the console is 500 internal server error: Error: EROFS: read-only file system, open &#39;/snap/quassel-webserver/x1/lib/node_modules/quassel-webserver/public/stylesheets/theme-default.css&#39;<br> &nbsp; &nbsp;at Error (native)

This happens every time I try to access a css file from the stylesheets directory. But it happens only the first time. I see that you are serving the files with express.static. I've been trying to understand why it would complain when opening the file if the file system is read-only, but so far I haven't found anything.

I find it strange that this happens only for the css files. The icon is served ok.

Do you have any ideas?

**Comment by elopio** [comment]
Hey, I got it! It's the less middleware.
Is there a way to send the compiled css to a direcctory in HOME or XDG?

**Comment by elopio** [comment]
@magne4000 please check if my fix makes sense at all.

**Comment by magne4000** [comment]
I tried the `cacheFile` option of `less-middleware`, but the cache is valid just for the machine on which it has been generated. So using `dest` option instead seems to be a good solution. You can confirm that you have no more error with it ?

**Comment by elopio** [comment]
@magne4000 yes, I tested it in a xenial kvm.

**Comment by magne4000** [comment]
Thanks !

**Comment by elopio** [comment]
Thanks to you @magne4000! 
Now you can register and upload the snap, to give it a try: https://myapps.developer.ubuntu.com/dev/click-apps/register-name/
And if you want, we can hook travis and the store to make automatic releases to the edge channel, and get feedback from your early adopters. I have some scripts here to get started, let me know if I should make a PR.

**Comment by magne4000** [comment]
@elopio feel free to share this hook scripts :)

**Pull request merged**
