### PR TITLE
Add install instructions from npm and snap

### PR DESCRIPTION
**Pull request by elopio**

### CODE REVIEW

**Comment by elopio** [comment]
Hey @magne4000, what do you think about mentioning the snap in the README, to get more people trying it?
Once you think you have a version ready, you can move it to the candidate channel and we can make a call for testing in the Ubuntu community.

Happy new year!

**Comment by magne4000** [comment]
@elopio builds are now candidate ready, I just promoted rev 10 to this channel.
Do you hav to update this PR to take this into account ?

**Comment by elopio** [comment]
@magne4000 I updated it.

**Comment by magne4000** [comment]
Thanks !

**Pull request merged**
