### PR TITLE
Build the snap in travis

### PR DESCRIPTION
**Pull request by elopio**

### CODE REVIEW

**Comment by elopio** [comment]
ping @magne4000. To test this, you have to enable the travis integration for your repository.

**Comment by magne4000** [comment]
https://travis-ci.org/magne4000/quassel-webserver
```Snapped quassel-webserver_master_amd64.snap```
:+1:

**Comment by elopio** [comment]
Thank you @magne4000 ! now to hook this with daily releases, the first step is for you to register the name, because this should be done with your credentials, not mine.
https://myapps.developer.ubuntu.com/dev/click-apps/register-name/

I suggest you to upload a snap to the edge channel, so you can give it a try and start looking around.

**Comment by magne4000** [comment]
I just published the snap under `quassel-webserver` on Edge channel.

**Comment by elopio** [comment]
awesome @magne4000! We are working on a snapcraft command to configure the automated pushes from travis. How busy are you? As this is not released yet, setting it up is still a little messy. Would you like to jump into a hangout or irc chat so I can guide you to give it a try? This needs your credentials, so I can't do it from here, and bonus points that you would help us testing it :)

Alternatively, I can write down some steps so you do it manually without snapcraft when you have a chance. If you are curious, we are basing our work on this: https://gist.github.com/evandandrea/c754964bfdfb176844f26f605ebbb8db

pura vida

**Comment by magne4000** [comment]
You can ping me on Freenode, I'm **Magne`** (you can find me on #quassel)

**Pull request merged**
