### PR TITLE
Update libquassel to version 2.1.3

### LINKED ISSUE #220: quassel-webserver candidate snap fails to connect
Hey @magne4000,

I'm trying the candidate snap, and it gets stuck during connection. The quassel-core log shows:

2017-01-13 13:32:59 Warning: "Socket error 13: Error during SSL handshake: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol" 
2017-01-13 13:32:59 Info: Non-authed client disconnected: 127.0.0.1 

Do you have any idea of what could be causing this?

I'm testing in Ubuntu 16.04.

```
$ snap list
Name               Version  Rev  Developer  Notes
core               16.04.1  714  canonical  -
quassel-webserver  master   10   magne4000  -
```

Here are the steps to reproduce: https://gist.github.com/elopio/e8a5214aa89a320ebd505b5dc184e2df

### PR DESCRIPTION
**Pull request by elopio**
Fixes #220

### CODE REVIEW

**Comment by magne4000** [comment]
I'll merge dev before tagging a new version with this, thanks !

**Comment by elopio** [comment]
Thank you for reviewing @magne4000. Let me know when you push the following tag to candidate, and then we can finally make that call for testing on the ubuntu QA mailing list :)

**Comment by magne4000** [comment]
`2.2.6` published onto `candidate`

**Comment by elopio** [comment]
@magne4000 here it is: https://lists.ubuntu.com/archives/ubuntu-quality/2017-February/006767.html ^_^

**Comment by magne4000** [comment]
:tada:

**Pull request merged**
