### PR TITLE
Update darkmonokai

### PR DESCRIPTION
**Pull request by Zren**
image

### CODE REVIEW

**Comment by Zren** [comment]
Added another commit with some more changes.

All Themes

* Shorter lineheight in the topic, and show an ellipsis if text is hidden.
* Use same font in the topic as the backlog.
* Make the corner between hor/vert webkit scrollbars transparent.

Darkmonokai

* Darken topic
* Use text color instead of a background gradient to show channel newmessage/hightlight.
47ed
* Color the webkit scrollbars instead of using a transparent black. (Forgot to put this in the commit message).

**Comment by magne4000** [comment]
Nice ! :+1:

**Comment by magne4000** [comment]
white-space: nowrap on firefox have some weird behavior when topic is too long, channels and user list are hidden, instead of just truncating the topix with elipsis

**Comment by Zren** [comment]
Bloody hell. Gotta remember to test other browsers.

Looks like there's a merge conflict with the other pr, I'll fix that.

**Comment by magne4000** [comment]
I just merge the other PR

**Pull request merged**
