### PR TITLE
Use settings-user.js if it exists instead of settings.js which is tracked by git.

### PR DESCRIPTION
**Pull request by Zren**
It's mildly annoying having the settings file tracked by git, which could possibly cause merge conflicts if you update. That and you can't do "git add all".

### CODE REVIEW

**Comment by magne4000** [comment]
I made myself the same reflexion on last commits. But settings.js is used on others files too, so i need to make a function to handle the issue I think.

**Comment by Zren** [comment]
Ah. Can always add

```javascript
if (require('fs').existsSync('./settings-user.js')) {
    module.exports = require('./settings-user.js');
}
```

to the bottom of `settings.js`.

**Comment by magne4000** [comment]
Good idea, but if you copy settings.js to settings-user.js, you would need to delete those lines. I know that's not a big issue, but I think making dumb method will also do the trick

**Comment by Zren** [comment]
Also forgot to add `settings-user.js` to the `.gitignore` (I added it to `.git/info/exclude` and forgot about it).

**Pull request closed without merging**
